apiVersion: v1
kind: Service
metadata:
  name: welcome-app-svc
  labels:
    app: welcome-app
spec:
  type: LoadBalancer
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: welcome-app
